// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// updateQv
List updateQv(arma::vec v, arma::mat Qr);
RcppExport SEXP _boss_updateQv(SEXP vSEXP, SEXP QrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Qr(QrSEXP);
    rcpp_result_gen = Rcpp::wrap(updateQv(v, Qr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boss_updateQv", (DL_FUNC) &_boss_updateQv, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_boss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
